source 'https://rubygems.org'

gem 'rails', '4.0.4'

gem 'bootstrap-sass'
gem 'carrierwave-video'
gem 'coffee-rails',     '~> 4.0.0'
gem 'high_voltage'
gem 'jbuilder',         '~> 1.2'
gem 'jquery-rails'
gem 'mysql2'
gem 'rmagick',          '~> 2.13.2'
gem 'sass-rails',       '~> 4.0.2'
gem 'simple_form'
gem 'slim'
gem 'turbolinks'
gem 'uglifier',         '>= 1.3.0'
gem 'unicorn'
