development:
  adapter: mysql2
  encoding: utf8
  database: chromecastyourself_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: chromecastyourself_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: chromecastyourself_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
